CREATE DATABASE STUDENT_MANAGEMENT
GO
USE STUDENT_MANAGEMENT
GO
CREATE TABLE STUDENT(
	STUDENT_ID VARCHAR(20),
	STUDENT_NAME NVARCHAR(100),
	STUDENT_GPA FLOAT,
	STUDENT_IMAGES VARCHAR(30),
	STUDENT_ADDRESS NVARCHAR(50),
	STUDENT_NOTES NVARCHAR(100)
)
GO
INSERT INTO STUDENT VALUES('19127640', N'Hoang Huu Giap', 9.5, 'giap.jpg', '227 Nguyen Van Cu District 5 HCM', 'nothing')
INSERT INTO STUDENT VALUES('19127641', N'Nguyen Van Trung', 6.5, 'trung.jpg', '228 Nguyen Van Cu District 5 HCM', 'nothing')
INSERT INTO STUDENT VALUES('19127642', N'Tran Van Hai', 2.4, 'hai.jpg', '229 Nguyen Van Cu District 5 HCM', 'nothing')
INSERT INTO STUDENT VALUES('19127643', N'Nguyen Bao Tram', 1.5, 'tram.jpg', '230 Nguyen Van Cu District 5 HCM', 'nothing')